### ISSUE TITLE
AbstractController::Helpers::MissingHelperError in WelcomeController#index

### ISSUE THREAD

**Issue by godiveau** [acaciasforall/acacias-harvest#3]
Bonjour,
j'ai installé en local un fork, tout va bien je lance le server rails ça fonctionne aussi mais erreur à l'affichage de l'index : 
 
AbstractController::Helpers::MissingHelperError (Missing helper file helpers//volumes/data/_privÉ/_hubic/dropbox/_programmation/foad_simplon/_ruby/acacias_harvest/app/helpers/application_helper.rb_helper.rb):
  app/controllers/application_controller.rb:1:in `<top (required)>'
  app/controllers/welcome_controller.rb:1:in `<top (required)>'

Une idée ?
Merci.

**Comment by FrenchFlakito** [comment]
Hello,

Aucun problème pour moi, je ne sais pas trop ce qui cloche pour toi... Essaye de regarder par là ?
https://www.google.fr/search?client=ubuntu&channel=fs&q=AbstractController%3A%3AHelpers%3A%3AMissingHelperError+%28Missing+helper+file+helpers%2F%2Fvolumes%2Fdata&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=Xw65VNbYFeqk0AW12IG4BQ

**Comment by godiveau** [comment]
Hello,
bien sûr que j'ai été sur google !
;-)

merci quand même je vais continuer à creuser.

Bien à toi.




2015-01-16 14:13 GMT+01:00 FrenchFlakito <notifications@github.com>:

**Comment by godiveau** [comment]
Bon j'ai trouvé
c'est une question d'accent et de majuscule dans mon chemin trèèèès long.

j'ai posé sur le bureau et là miracle !


merci


2015-01-16 14:13 GMT+01:00 FrenchFlakito <notifications@github.com>:

**Comment by FrenchFlakito** [comment]
GG, GG !
 ;-)

**Comment by FrenchFlakito** [comment]
Issue to be closed.
